// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG7UnRP0c0jG-zMtWVf6_1Mdza8VNz0ZE',
    appId: '1:735101162067:web:f602328a1db693bae5eca6',
    messagingSenderId: '735101162067',
    projectId: 'mobile-skripsi',
    authDomain: 'mobile-skripsi.firebaseapp.com',
    storageBucket: 'mobile-skripsi.firebasestorage.app',
    measurementId: 'G-XCFF3XWN4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_67AS-ewtlYFEEo3gX33oP6_JHyAKmvk',
    appId: '1:735101162067:android:3a50e722a50ecfcee5eca6',
    messagingSenderId: '735101162067',
    projectId: 'mobile-skripsi',
    storageBucket: 'mobile-skripsi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr__E35d1ZVnwiuld4x2dg2jSs3X8iiT4',
    appId: '1:735101162067:ios:d2103771e7738a15e5eca6',
    messagingSenderId: '735101162067',
    projectId: 'mobile-skripsi',
    storageBucket: 'mobile-skripsi.firebasestorage.app',
    iosBundleId: 'com.example.safevision',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr__E35d1ZVnwiuld4x2dg2jSs3X8iiT4',
    appId: '1:735101162067:ios:d2103771e7738a15e5eca6',
    messagingSenderId: '735101162067',
    projectId: 'mobile-skripsi',
    storageBucket: 'mobile-skripsi.firebasestorage.app',
    iosBundleId: 'com.example.safevision',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG7UnRP0c0jG-zMtWVf6_1Mdza8VNz0ZE',
    appId: '1:735101162067:web:d172f56860c5bfa1e5eca6',
    messagingSenderId: '735101162067',
    projectId: 'mobile-skripsi',
    authDomain: 'mobile-skripsi.firebaseapp.com',
    storageBucket: 'mobile-skripsi.firebasestorage.app',
    measurementId: 'G-S8Z05XLQKX',
  );
}
